# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        include_format: false
        default_format: json
    view:
        view_response_listener: true
    body_listener:
        enabled: true
    body_converter:
        enabled: true
        validate: true
    param_fetcher_listener:
        enabled: true
    serializer:
        serialize_null: true
    format_listener:
        rules:
          - { path: '^/api/doc', stop: true }
          - { path: '^/api', priorities: ['json'], fallback_format: json }
    zone:
        - { path: ^/api/* }