nelmio_api_doc:
    documentation:
        info:
            title: SF Basket API - Documentation
            description: Documentation de l'API REST SF Basket
            version: 1.0
    areas:
        path_patterns:
        - ^/api/(?!doc)